version: "3"

services:
  mysqldb:
    container_name: mysqldb
    hostname: mysqldb
    image: mysql/mysql-server:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: ttapp
    ports:
      - "3306:3306"
    volumes:
      - mysqldb-data:/var/lib/mysqldb/data
    networks:
      - mynetwork

  ttapp:
    container_name: ttapp
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynetwork

volumes:
  mysqldb-data:

networks:
  mynetwork:
    driver: bridge